---
output: github_document
title:  Exploring Pulse Interventions
---

<!-- README.md is generated from README.Rmd. Please edit that file -->
Pulse interventions can also be explored


* First, load in the libraries.

```{r,message=F}
library(seirR)
library(ggplot2)
library(readsdr)
library(tidyr)
library(dplyr)
```

* Create the model, and setup the pulse intervention variable

```{r}
mod <- create_seir_p()

mod <- set_param(mod,"Distancing_Switch",1)
mod <- set_param(mod,"Pulse_Switch",1)
mod <- set_param(mod,"Switch_Time",60) # time to switch to Pulse strategy
mod <- set_param(mod,"Percentage_Reduction_of_Physical_Distancing",.6)
```

* Run the model and extract 3 variables of interest

```{r}
out1 <- run(mod)

tb <- out1 %>% select(SimDay,Reported_Incidence,
                      Physical_Distancing_Smoothed_Value,Pulse_Policy) %>%
               pivot_longer(-SimDay,names_to="Variable", values_to = "Value")
```


* Display the results
```{r}
ggplot(tb,aes(x=SimDay,y=Value,colour=Variable))+
  facet_grid(Variable~.,scales = "free_y")+
  geom_point()+geom_line()
```



